mercurius-js/cache

- README.md
- examples/cache-per-user.js
- index.js
- package.json
- test/extend-key.test.js
The idea is to to append data to the caching key in order to allow private content caching, as in the example `custom-key.js`
~~The PR is a draft~~
> feat: custom key

- README.md
- index.js
- test/base.test.js
- test/extend-key.test.js
Proposal: rename `remoteCache` option to `storage`
> chore: rename remoteCache to storage

- index.js
- test/base.test.js
This PR makes the cache skip mutations
Closes #26
> Skip mutations

- index.js
@simone-sanfratello as per Simone's instructions:
> we should use fastify's plugin mechanism to do this, exposed by fastify-plugin.
I made this quick change. please let me know your thoughts
> fix: validate mercurius is already registered

- test/report.test.js
PR removes failing test to fix the CI. I will fix and add the test back later
> Remove failing test

- index.js
- test/report.test.js
This PR adds skip count to the cache report
Closes #46
> Skip count reporting

- .github/workflows/ci.yml
> Upgrade automerge action to v3

- index.d.ts
- package.json
- test/types/index.test-d.ts
- tsconfig.json
I've added type definition file and also will be adding tests for them.
Closes #57
> feat: Add TS type definitions

- index.js
- package.json
- test/base.test.js
Closes: [#60](https://github.com/mercurius-js/cache/issues/60)
> fix: skipping subscriptions on cache

- .github/workflows/ci.yml
- README.md
- package.json
- test/redis-invalidation.test.js
I have created a file for redis invalidation tests
Closes #59
> test: Add redis tests for invalidation

- test/base.test.js
> fix: fixing mutation test

- index.js
- test/base.test.js
This PR implements the listener for the [`onError` "event"](https://github.com/mcollina/async-cache-dedupe/pull/13) from `async-cache-dedupe`.
The changes on line 155 where required, since that `await` can throw an exception (contrary to what the old comment above it says). That would cause the error to be sent to `onError` twice.
Closes #66
> feat: listen to async-cache-dedupe onError

- bench/gateway-invalidations.js
- bench/gateway-service-1.js
- bench/gateway-service-2.js
- index.js
- test/base.test.js
> add benchmarks for invalidations. Fix a few bugs noticed when developing them

- index.js
- test/base.test.js
This PR tries to simplify the error handling in the code. I have tried to split the different conditionals into separate functions so that the code is more readable. Added some tests to ensure we cover all cases and coverage is 💯 
Closes #76
> Refactored Error handling

- README.md
- index.js
- lib/validation.js
- test/base.test.js
- test/lib-validation.test.js
Implementing _options for nested fields conflicts
closes #61
> feat: __options policy implementation

- examples/invalidation.js
Adds an invalidation example with a simple schema.
Closes #73
> Add an invalidation example

- index.d.ts
- lib/validation.js
- test/lib-validation.test.js
> fix: Storage invalidation options

- README.md
- examples/invalidation.js
- index.js
- package.json
- test/with-redis.test.js
following https://github.com/mcollina/async-cache-dedupe/pull/19
> feat: wildcard invalidation

- index.d.ts
> chore: adding missing types on invalidate function

- package.json
> chore: update deps - fix memory leak in async-cache-dedupe

- index.js
- test/base.test.js
> fix: thows error on orignal resolver error

- examples/invalidation-with-subscription.js
> feat: add invalidation with subscription example

- examples/gateway-federation.js
> feat: add federation and gateway examples

- README.md
- lib/report.js
> docs(#128): improve documentation how the plugin works

- .github/tests_checker.yml
- .github/workflows/ci.yml
Proposal:
- added `node v24.x` 🔥 in the `ci.yml` file
> chore: added node v24.x in the ci.yml file and updated

- LICENSE
- examples/basic.js
- examples/cache-per-user.js
- examples/invalidation.js
- examples/policy-options.js
- examples/redis.js
Proposals:
- Updated examples for Fastify v5.x 🔥
- Update `LICENSE` for the year 2025 🔥
> chore: update examples for fastify v5.x and license
